
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Anatasya
 */

public class Klinik extends javax.swing.JFrame {

        Connection con = null;
	ResultSet rs = null;
	PreparedStatement pst = null;
	Statement statpas;
	Boolean ada = false;
        
    private void config() {
	try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost/klinik"; //url database
            String user="root"; //user database
            String pass=""; //password database
            con = DriverManager.getConnection(url,user,pass);
            statpas = con.createStatement(rs.TYPE_SCROLL_SENSITIVE,rs.CONCUR_UPDATABLE);
            rs = statpas.executeQuery("select * from pasien");
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                System.exit(0);
            }
    }

     private void display(){
        try{
            String sql="select * from pasien";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            TbPas.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
    /**
     * Creates new form Klinik
     */

    public Klinik() {
        initComponents();
        config();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFNama = new javax.swing.JTextField();
        TFNik = new javax.swing.JTextField();
        DCTanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAlamat = new javax.swing.JTextArea();
        BtSimpan = new javax.swing.JButton();
        BtCreate = new javax.swing.JButton();
        BtDel = new javax.swing.JButton();
        BtUpdate = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbPas = new javax.swing.JTable();
        TFid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Data Pasien");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("NIK");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Tanggal Lahir");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        TFNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaActionPerformed(evt);
            }
        });
        getContentPane().add(TFNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 241, -1));

        TFNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNikActionPerformed(evt);
            }
        });
        getContentPane().add(TFNik, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 241, -1));

        DCTanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DCTanggalPropertyChange(evt);
            }
        });
        getContentPane().add(DCTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 241, -1));

        TAlamat.setColumns(20);
        TAlamat.setRows(5);
        jScrollPane1.setViewportView(TAlamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 240, 100));

        BtSimpan.setText("Simpan");
        BtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BtSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 367, -1));

        BtCreate.setText("Tambah");
        BtCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCreateActionPerformed(evt);
            }
        });
        getContentPane().add(BtCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 120, -1));

        BtDel.setText("Hapus");
        BtDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDelActionPerformed(evt);
            }
        });
        getContentPane().add(BtDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 120, -1));

        BtUpdate.setText("Update");
        BtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(BtUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 120, -1));

        TbPas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "NIK", "Tanggal Lahir", "Alamat"
            }
        ));
        TbPas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbPasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TbPas);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 720, 180));
        getContentPane().add(TFid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 240, -1));

        jLabel6.setText("Nama");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        BtKeluar.setText("Keluar");
        BtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(BtKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaActionPerformed

    private void BtCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCreateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtCreateActionPerformed

    private void BtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSimpanActionPerformed
        // TODO add your handling code here:
        
        String tgl = "yyyy MMM dd";
        SimpleDateFormat fm = new SimpleDateFormat(tgl);
        String tanggal = String.valueOf(fm.format(DCTanggal.getDate()));
        try{
            config();
            statpas = con.createStatement();
            String SQL = "insert into pasien values"
                    + "('"+TFid.getText()+"','"+TFNama.getText()+"','"
                    +TFNik.getText()+"','"+tanggal+"','"
                    +TAlamat.getText()+"')";

            statpas.executeUpdate(SQL);
            display();
            statpas.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
//            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_BtSimpanActionPerformed

    private void TFNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNikActionPerformed

    private void DCTanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DCTanggalPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_DCTanggalPropertyChange

    private void BtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtUpdateActionPerformed
        // TODO add your handling code here:
        String tgl = "yyyy MMM dd";
        SimpleDateFormat fm = new SimpleDateFormat(tgl);
        String tanggal = String.valueOf(fm.format(DCTanggal.getDate()));
        try{
            config();
            statpas = con.createStatement();
            String SQL = "update pasien SET id = '"+TFid.getText()+"','"+TFNama.getText()+"','"
                    +TFNik.getText()+"','"+tanggal+"','"
                    +TAlamat.getText()+"'";
            statpas.executeUpdate(SQL);
            display();
            statpas.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BtUpdateActionPerformed

    private void BtDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDelActionPerformed
        // TODO add your handling code here:
        try{
            config();
            statpas = con.createStatement();
            String SQL = "DELETE FROM pasien WHERE id = '"+TFid.getText()+"'";
            statpas.executeUpdate(SQL);
            display();
            statpas.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BtDelActionPerformed

    private void BtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtKeluarActionPerformed

    private void TbPasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbPasMouseClicked
        // TODO add your handling code here:
        String tgl = "yyyy MMM dd";
        SimpleDateFormat fm = new SimpleDateFormat(tgl);
//        String tanggal = String.valueOf(fm.format(DCTanggal.getDate()));
        try {
            config();
            int row =TbPas.getSelectedRow();
            String tabel_klik=(TbPas.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from pasien where id='"+tabel_klik+"'");
            if(sql.next()){
                String id = sql.getString("id");
                TFid.setText(id);
                String nama = sql.getString("nama");
                TFNama.setText(nama);
                String nik = sql.getString("nik");
                TFNik.setText(nik);
                String tanggal = String.valueOf(fm.format(DCTanggal.getDate()));
                DCTanggal.setDateFormatString(tanggal);
                String alamat = sql.getString("alamat");
                TAlamat.setText(alamat);
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_TbPasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Klinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Klinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Klinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Klinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Klinik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCreate;
    private javax.swing.JButton BtDel;
    private javax.swing.JButton BtKeluar;
    private javax.swing.JButton BtSimpan;
    private javax.swing.JButton BtUpdate;
    private com.toedter.calendar.JDateChooser DCTanggal;
    private javax.swing.JTextArea TAlamat;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFNik;
    private javax.swing.JTextField TFid;
    private javax.swing.JTable TbPas;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
